services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./..
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      XDEBUG_SESSION: ${XDEBUG_IDE_KEY}
    volumes:
      - ./../:/var/www

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

  mysql:
    container_name: mysql
    build:
      context: ./mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command:
      - --mysql-native-password=ON
    restart: unless-stopped
    volumes:
      - docker-data:/var/lib/mysql

volumes:
  docker-data: